#!/bin/bash

dotfiles=$PWD

die() {
  echo >&2 "$1" && exit 1
}

link() {
  [[ -z $2 ]] && target=".${1##*/}" \
              || target="${2:-$target}"

  [[ -e "$target" && ! -h "$target" ]] && die "$0: $target exists in filesystem"
  [[ -d "$target"                   ]] && rm "$target"

  ln -fs "$dotfiles/$1" "$target"
}

# Deploy scriptlets {{{1
dotfiles_cower()       { link cower .config/cower;                     }
dotfiles_dircolors()   { link dircolors/dircolors;                     }
dotfiles_git()         { link git/gitconfig;                           }
dotfiles_htop()        { link htop/htoprc;                             }
dotfiles_lxdm()        { link lxdm/dmrc;                               }
dotfiles_ncmpcpp()     { link ncmpcpp;                                 }
dotfiles_mutt()        { link mutt;                                    }
dotfiles_nethack()     { link nethack/nethackrc;                       }
dotfiles_pam()         { link pam/pam_environment;                     }
dotfiles_pentadactyl() { link pentadactyl/pentadactylrc;               }
dotfiles_termite()     { link termite/termite.cfg .config/termite.cfg; }
dotfiles_tmux()        { link tmux/tmux.conf;                          }
dotfiles_weechat()     { link weechat;                                 }
dotfiles_xmonad()      { link xmonad;                                  }

dotfiles_task() {
  link task/task
  link task/taskrc
}

dotfiles_vim() {
  link vim
  link vim/vimrc
  link vim/gvimrc
}

dotfiles_X() {
  link X/Xresources
  link X/xinitrc
  link X/gtkrc-2.0 .gtkrc-2.0.mine
}

dotfiles_zsh() {
  link zsh/zshrc
  link zsh/zprofile
}
# }}}

usage() {
  cat << HERE
Automated deploy function for dotfile syncronization.

SUPPORTED:
HERE

  for fun in $(compgen -A function dotfiles_); do
    echo "  ${fun#dotfiles_}"
  done
  exit ${1:-0}
}

deploy() {
  while (( $# )); do
    cd && dotfiles_${1#dotfiles_}
    if [[ $? == 127 ]]; then
      echo  >&2 "Error: don't know how to deploy \"$1\""
      usage >&2 1
    fi
    shift
  done
}

if (( $# == 0 )); then
  deploy $(compgen -A function dotfiles_)
elif [[ "$1" == "--help" ]]; then
  usage 0
else
  deploy $*
fi
