#!/bin/bash

dotfiles=$PWD
cd ~

while (($#)); do
  case "$1" in
    "vim")
      ln -fs $dotfiles/vim .vim
      ln -fs .vim/vimrc .vimrc
      ln -fs .vim/gvimrc .gvimrc
      ;;
    "ncmpcpp")
      ln -fs $dotfiles/ncmpcpp .ncmpcpp
      ;;
    "xmonad")
      ln -fs $dotfiles/xmonad .xmonad
      ln -fs $dotfiles/xmobarrc .xmobarrc
      ;;
    "x"|"xorg")
      ln -fs $dotfiles/Xresources .Xresources
      ln -fs $dotfiles/xinitrc .xinitrc
      ln -fs $dotfiles/gtkrc-2.0 .gtkrc-2.0.mine
      ;;
    "tmux")
      ln -fs $dotfiles/tmux.conf .tmux.conf
      ;;
    "git")
      ln -fs $dotfiles/gitconfig .gitconfig
      ;;
    "htop")
      ln -fs $dotfiles/htoprc .htoprc
      ;;
    *)
      echo "$0: deploy command $1 not understood"
      ;;
  esac
  shift
done
