" file:     ~/.vimrc files
" author:   Simon Gomizelj
" ----------------------------------------------------------------------------

set nocompatible

filetype off
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

syntax on
filetype plugin indent on
colorscheme diablo3

" GENERAL {{{1
" -----------------------------

" formatting
set tabstop=4
set shiftwidth=4
set softtabstop=2
set cinoptions=(0
set smartindent
set linebreak
set nowrap
set textwidth=72
set wrapmargin=0
set whichwrap+=<,>,[,],h,l
set formatoptions=qn1

" searching
set hlsearch
set smartcase
set incsearch

" editing
set list listchars=tab:→\ ,extends:$,precedes:^,trail:-
set nrformats+=alpha

" folding
set foldenable
set foldmethod=marker
set foldmarker={{{,}}}
set foldcolumn=1
set backspace=indent,eol,start

" spelling
set spelllang=en_ca
set spellfile=~/.vim/dict.add

" vim ui
set autoread
set autowrite
set showcmd
set title
set ruler
set number
set cursorline
set shortmess=at
set hidden
set laststatus=2
set scrolloff=3
set wildmenu wildmode=list:longest,full
set completeopt=longest,menuone
set history=50
set confirm
set equalalways
set lazyredraw

if has('mouse')
  set mouse=a
endif

set wildignore+=.hg,.git,.svn                  " version control
set wildignore+=*.aux,*.out,*.toc              " LaTeX intermediate files
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg " images files
set wildignore+=*.a,*.o,*.obj,*.so,*.hi        " compiled object files
set wildignore+=*.pyc                          " python byte code
set wildignore+=*.spl                          " compiled spell lists

" backup
set dir=~/.vim/tmp
set backup   backupdir=~/.vim/backups
set undofile undodir=~/.vim/undo

" AUTOCMDS {{{1
" ----------------------------
au VimResized   * exe "normal! \<c-w>="
au BufWritePost * if getline(1) =~ "^#!" | silent :!chmod +x <afile>

" MAPPINGS {{{1
" ----------------------------

" for common typos
command! Q q
command! W w
command! Qa qa
command! Wq wq
command! Wa wa
command! Wqa wqa

command! Ww w !wc -w

" sane j k actions
nnoremap j gj
nnoremap k gk

" map Y to act like D and C; yank till end of line
noremap Y y$

nnoremap <silent> <leader>c :call toggle#ToggleList("Quickfix List", 'c')<CR>
nnoremap <silent> <leader>d :diffupdate<CR>
nnoremap <silent> <leader>h :nohl<CR>
nnoremap <silent> <leader>l :ls<CR>:b<space>
nnoremap <silent> <leader>s :setl spell!<CR>
nnoremap <silent> <leader>p :!pastebin "%"<CR>
nnoremap <silent> <leader>x :silent! call spaces#StripTrailing()<CR>

" strip trailing spaces
noremap <silent> <leader>w :call spaces#StripTrailing()<CR>

" window movements
nnoremap <silent> <C-H> :winc h<CR>
nnoremap <silent> <C-J> :winc j<CR>
nnoremap <silent> <C-K> :winc k<CR>
nnoremap <silent> <C-L> :winc l<CR>

" map space to create/open/close fold
nnoremap <silent> <Space> @=(foldlevel('.')?'za':'l')<CR>
vnoremap <Space> zf

" changing dictionaries
command! Fr setl spelllang=fr
command! En setl spelllang=en_ca
command! Sl setl spelllang=sl

" bindings for building code
nnoremap <F5>   :make<CR>
nnoremap <S-F6> :!./"%"<CR>

" PLUGINS {{{1
" ----------------------------

" set vim to download files with curl
let g:netrw_http_cmd  = "curl"
let g:netrw_http_xcmd = "-so"

" NERDTree config
let g:NERDTreeChDirMode     = 2
let g:NERDTreeIgnore        = ['\~$', '\.swp$', '\.o$', '\.hi$']
let g:NERDTreeSortOrder     = ['^__\.py$', '\/$', '*', '\~$']
let g:NERDTreeShowBookmarks = 1
let g:NERDTreeMinimalUI     = 1
nnoremap <silent> <F9> :NERDTreeToggle<CR>

" gundo config
nnoremap <silent> <leader>u :GundoToggle<CR>

" fugative config
nnoremap <leader>gg :copen<CR>:Ggrep 
nnoremap <silent> <leader>gs :Gstatus<CR>
nnoremap <silent> <leader>gd :Gdiff<CR>
nnoremap <silent> <leader>ge :Gedit<CR>
nnoremap <silent> <leader>gb :Gblame<CR>

" ghc-mod config
nnoremap <silent> <leader>hc :GhcModCheck<CR>
nnoremap <silent> <leader>hl :GhcModLint<CR>

" tagbar config
nnoremap <silent> <leader>t :TagbarToggle<CR>

" tabular config
noremap <silent> <leader>a= :Tabular /=<CR>
noremap <silent> <leader>a: :Tabular /[^:]\+:<CR>
noremap <silent> <leader>a, :Tabular /[^,]\+,<CR>

" youcompleteme config
let g:ycm_global_ycm_extra_conf = '~/.vim/ycm/c_conf.py'
nnoremap <silent> <leader>y :YcmDiag<CR>

" pandoc config
let g:pandoc_no_empty_implicits = 1
let g:pandoc_no_spans           = 1
let g:pandoc_no_folding         = 1

" utilsnips config
let g:UltiSnipsSnippetsDir         = "~/.vim/snippets"
let g:UltiSnipsExpandTrigger       = "<c-j>"
let g:UltiSnipsJumpForwardTrigger  = "<c-j>"
let g:UltiSnipsJumpBackwardTrigger = "<c-k>"
