#!/bin/bash

cd

if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [[ -x "$f" ]] && . "$f"
  done
  unset f
fi

launch() {
  type ck-launch-session && exec ck-launch-session $*
  exec $*
}

case ${2:-xmonad} in
  xbmc)
    exec xbmc-standalone ;;
  gnome)
    launch gnome-session ;;
  xmonad)
    launch xmonad ;;
  *)
    echo >&2 "Unrecognized command $2"
    exit 1;
esac
